a = 10;
l = 15;
b = 15;
h = 15;
area = 6*a*a;
volume = a*a*a;
perimeter = 4*(l+b+h);
console.log("area of cube is "+area);
console.log("volume of cube is "+volume);
console.log("perimeter of cube is "+perimeter);
